name: 'Minify JavaScript'
description: 'Minify JavaScript source files to min.js files'
inputs:
  target:
    description: 'Glob target directory or file to minify'
    required: true
  destination:
    description: 'Location for the minified sources (defaults to target)'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
