name: 'Compile Less'
description: 'Compile less -> css'
inputs:
  target:
    description: 'Glob target directory or file to compile'
    required: true
  destination:
    description: 'Location for the compiled sources (defaults to target)'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
