name: 'Compile Frontend'
description: 'Compile frontend code'
inputs:
  target:
    description: 'glob target to compile'
    required: true
outputs:
  modified_files:
    description: 'Number of files modified'
  commit_sha:
    description: 'Hash of created commit'
runs:
  using: 'node12'
  main: 'index.js'
