name: Test minify js
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jrdh/compile-frontend-action/js@master
        with:
          target: 'js/*'
