name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - uses: jrdh/compile-frontend-action
        with:
          target: 'beans/lemons/*'
          destination: 'beans/lemons/'
            
